source "https://rubygems.org"

#path '../'

gemspec

platforms :jruby do
  path '../' do
    gem 'jdbc-sqlite3', '~> 3.28'
    gem 'do_jdbc'
  end

end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake'
end
