source "https://rubygems.org"

path '../'

gemspec

platforms :jruby do
  gem 'jdbc-openedge'
  gem 'do_jdbc'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake'
  # gem 'rake-compiler'
end
